### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by anandrajneesh** [tahazayed/BotConnectorSkypeForBusiness#1]
Hi,

Can you please elaborate how to run this code, sorry for being total noob here but I have no experience in .NET or related at all. I have managed to get it build though had some problems with locating lync dlls.
Do i have to attach it to the lync process?

**Comment by tahazayed** [comment]
Hi,
You have to install lync SDK from this url
https://www.microsoft.com/en-eg/download/details.aspx?id=36824
